Repository vaadin/vaadin-combo-box, pull requests merged in 2018-10, with the labels that each got.

#725 Add dataProvider mixin
  demo/combo-box-basic-demos.html
  src/vaadin-combo-box-data-provider-mixin.html
  src/vaadin-combo-box-dropdown-wrapper.html
  src/vaadin-combo-box-light.html
  src/vaadin-combo-box-mixin.html
  src/vaadin-combo-box-placeholder.html
  src/vaadin-combo-box.html
  test/.eslintrc.json
  test/filtering.html
  test/lazy-loading.html
  test/test-suites.js
  test/vaadin-combo-box.html
Labels: in progress

#727 Data provider docs & demo [skip ci]
  demo/combo-box-basic-demos.html
  src/vaadin-combo-box-data-provider-mixin.html
  src/vaadin-combo-box.html
Labels: in progress

#729 Use filtered-countries in lazy loading demo [skip ci]
  demo/combo-box-basic-demos.html
Labels: in review unscoped

#733 Clear pending requests on clearCache
  src/vaadin-combo-box-data-provider-mixin.html
  test/lazy-loading.html
Labels: in review

#736 Don't throw with large size
  src/vaadin-combo-box-data-provider-mixin.html
  test/lazy-loading.html
Labels: in review

#739 Don't throw with large size on clearCache
  src/vaadin-combo-box-data-provider-mixin.html
  test/lazy-loading.html
Labels: in progress

#740 Avoid getting placeholders marked selected while loading
  src/vaadin-combo-box-dropdown-wrapper.html
  test/lazy-loading.html
Labels: in progress

#743 fix: add loader part and style loading items state
  demo/combo-box-basic-demos.html
  src/vaadin-combo-box-dropdown-wrapper.html
  src/vaadin-combo-box-dropdown.html
  test/lazy-loading.html
  test/vaadin-combo-box-dropdown.html
  theme/lumo/vaadin-combo-box-dropdown-styles.html
  theme/material/vaadin-combo-box-dropdown-styles.html
Labels: in progress

#744 Reuse the same placeholder instance
  src/vaadin-combo-box-data-provider-mixin.html
  test/lazy-loading.html
Labels: in review
